"""
Script that visualises and saves densepose results generated by apply_net.py in dump mode.
Only visualises for the largest person (largest bounding box) in the image.
"""

import sys
import pickle
import argparse
import numpy as np

from densepose.structures import DensePoseResult
sys.path.append("/data/cvfs/as2562/detectron2/projects/DensePose/")


def visualise_denspose_results(dump_file):
    with open(dump_file, 'rb') as f_results:
        data = pickle.load(f_results)

    # Loop through frames
    for entry in data:
        frame_fname = entry['file_name']
        print(frame_fname)

        # Choose the result instance (index) with largest bounding box
        bboxes_xyxy = entry['pred_boxes_XYXY'].numpy()
        print(bboxes_xyxy)
        bboxes_area = (bboxes_xyxy[:, 2] - bboxes_xyxy[:, 0]) \
                      * (bboxes_xyxy[:, 3] - bboxes_xyxy[:, 1])
        print(bboxes_area)
        largest_box_index = np.argmax(bboxes_area)
        result_encoded = entry['pred_densepose'].results[largest_box_index]
        iuv_arr = DensePoseResult.decode_png_data(*result_encoded)
        print(iuv_arr.shape, bboxes_xyxy[largest_box_index])

        I_image = iuv_arr[0,:,:]
        print(I_image.shape)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--dump_file', type=str)
    args = parser.parse_args()

    visualise_denspose_results(args.dump_file)
